const menu={bebidas:[
{name:"Café caliente",icon:"☕",items:[["Taza de café","$40"],["Espresso","$40"],["Espresso doble","$70"],["Cappuccino","$60"],["Latte","$60"],["Latte vainilla","$70"],["Latte caramelo","$70"],["Café moca","$80"],["Flat white","$70"],["Extras","","Leche vegetal $15 · Shot de café $30 · Vainilla $15 · Caramelo $10"]]},
{name:"Café frío",icon:"🧊",items:[["Café con hielo","$50"],["Latte con hielo","$80"],["Latte caramelo con hielo","$90"],["Latte vainilla con hielo","$90"],["Café moca frío","$90"],["Frappuccino","$80"],["Frappuccino Nutella","$100"],["Frappuccino caramelo","$90"],["Frappuccino vainilla","$90"],["Frappe espresso + cacao","$90"],["Latte frío + Baileys","$140"],["Mocca frío + Baileys","$140"],["Carajillo","$130","Espresso y Licor 43 en las rocas"]]},
{name:"Jugos naturales",icon:"🍊",items:[["Jugo verde","$80","Naranja, espinaca, piña, manzana verde, jengibre y apio"],["Jugo tropical","$80","Fresa, piña, naranja y menta"],["Jugo de naranja","$80"],["Naranja con fresa","$80"],["Naranja con papaya","$80"]]},
{name:"Licuados y smoothies",icon:"🍓",items:[["Smoothie","$80","Fresa, chocolate, plátano, mango, maracuyá o fruta de temporada"],["Licuado de avena con una fruta","$70","Fresa, plátano, manzana o fruta de temporada"],["Licuado de chocolate","$70"]]},
{name:"Otras bebidas",icon:"🥤",items:[["Naranjada","$60"],["Refresco","$45"],["Agua mineral","$35"],["Botella de agua","$25"],["Taza de té","$30"],["Jarra de agua frutal","$85","Naranja, naranja-fresa, piña-maracuyá, sandía o melón"]]},
{name:"Cócteles especiales",icon:"🥂",items:[["Carajillo","$130","Espresso y Licor 43 en las rocas"],["Mimosa","$140","Vino espumoso con naranja recién exprimida"]]}
],alimentos:[
{name:"Platillos mexicanos",icon:"🌮",items:[["Enchiladas","$180","En salsa verde, rellenas de pollo, queso de prensa, crema, cebolla y aguacate"],["Enchiladas suizas","$160","Salsa verde cremosa, gratinadas con manchego y rellenas de pollo"],["Entomatadas","$120","Salsa roja, huevos, queso de prensa, crema, cebolla y aguacate"],["Chilaquiles rojos o verdes","$120","Con huevos, queso de prensa, crema, cebolla y aguacate"],["Enfrijoladas","$120","Frijol, huevos, queso de prensa, crema, cebolla y aguacate"],["Nachos","$160","Chorizo, queso, crema, frijol y pico de gallo"],["Molletes","$120","Pan bolillo con chorizo o tasajo, queso, crema, frijol y pico de gallo"],["Cambio de proteína","$30","Chorizo, pollo o tasajo"]]},
{name:"Desayunos típicos",icon:"🍳",items:[["Huevos a tu elección","$100","Jamón, tocino, a la mexicana, chorizo o queso"],["Huevos divorciados","$110","Huevos con salsa roja y verde"],["Omelette tradicional","$130","Jamón y queso"],["Omelette de espinaca","$130","Espinaca y queso"],["Omelette de champiñón","$130","Champiñón y queso"],["Omelette de chorizo","$130","Chorizo y queso"],["Ingrediente extra para omelette","$15"],["Desayuno completo","$190","Huevos al gusto o chilaquiles con huevo; fruta con yogurt o jugo; café o té"]]},
{name:"Opciones saludables",icon:"🥑",items:[["Ensalada de frutas","$140","Frutas de temporada con yogurt, granola y frutos secos"],["Avocado toast","$140","Pan tostado, aguacate, tomate cherry y ajonjolí negro"],["AvoGato toast serrano","$160","Aguacate, jamón serrano, huevo, tomate cherry y ajonjolí. Queso azul +$20"],["Cereal artesanal","$80","Hojuelas artesanales, frutos secos, semillas y fruta de temporada"]]},
{name:"Hotcakes, pan y sándwiches",icon:"🥞",items:[["Hotcakes tradicionales","$120"],["Hotcakes especiales","$150"],["Pan francés","$130"],["Cuernito","$100"],["Cuernito especial","$130"],["Sándwich con huevo","$130"],["Sándwich","$90"],["Pan o postres","$50"]]}
]};
const tabs=document.querySelectorAll('.menu-main-tab'),categoryTabs=document.getElementById('categoryTabs'),items=document.getElementById('menuItems'),title=document.getElementById('categoryTitle'),path=document.getElementById('menuPath'),count=document.getElementById('itemCount');let section='bebidas',category=0;
function render(){const categories=menu[section],current=categories[category];categoryTabs.innerHTML=categories.map((c,i)=>`<button type="button" class="category-tab ${i===category?'active':''}" data-index="${i}" role="tab" aria-selected="${i===category}"><span>${c.icon}</span>${c.name}</button>`).join('');path.textContent=`${section==='bebidas'?'Bebidas':'Alimentos'} / ${current.name}`;title.textContent=current.name;count.textContent=`${current.items.length} opciones`;items.innerHTML=current.items.map(([name,price,description])=>`<article class="full-menu-item"><div><h4>${name}</h4>${description?`<p>${description}</p>`:''}</div>${price?`<strong>${price}</strong>`:''}</article>`).join('');categoryTabs.querySelectorAll('.category-tab').forEach(button=>button.addEventListener('click',()=>{category=Number(button.dataset.index);render()}))}
tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>{t.classList.toggle('active',t===tab);t.setAttribute('aria-selected',t===tab?'true':'false')});section=tab.dataset.section;category=0;render()}));render();